version: "3.8"
services:
    # postgres used by airflow
    postgres:
        image: postgres:14
        networks:
            - default_net
        volumes:
            # Create Test database on Postgresql
            - ./docker-airflow/pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"

    # airflow LocalExecutor
    airflow-webserver:
        image: docker-airflow-spark:2.4.0_3.3.0
        #image: docker-airflow-spark:1.10.7_3.1.2
        restart: always
        networks:
            - default_net
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY=Kd_dnSawBzNzDm--q93m7rjX7NWjb035EaATOcSLs_g=
        volumes:
            - ../dags:/usr/local/airflow/airflow/dags #DAG folder
            - ../spark/app:/usr/local/spark/app #Spark Scripts (Must be the same path in airflow and Spark Cluster)
            - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../output:/usr/local/spark/output # Output folder

        ports:
            - "8282:8282"
        command: webserver
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "[ -f /usr/local/airflow/airflow-webserver.pid ]"
                ]
            interval: 30s
            timeout: 30s
            retries: 3

    # Spark with 3 workers
    spark:
        image: bitnami/spark:3.3.0
        user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        hostname: spark
        networks:
            - default_net
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../output:/usr/local/spark/output # Output folder

        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: bitnami/spark:3.3.0
        user: root
        networks:
            - default_net
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
            - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
            - ../output:/usr/local/spark/output # Output folder
    # spark-worker-2:
    #     image: bitnami/spark:3.1.2
    #     user: root
    #     networks:
    #         - default_net
    #     environment:
    #         - SPARK_MODE=worker
    #         - SPARK_MASTER_URL=spark://spark:7077
    #         - SPARK_WORKER_MEMORY=1G
    #         - SPARK_WORKER_CORES=1
    #         - SPARK_RPC_AUTHENTICATION_ENABLED=no
    #         - SPARK_RPC_ENCRYPTION_ENABLED=no
    #         - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    #         - SPARK_SSL_ENABLED=no
    #     volumes:
    #         - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
    #         - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
    #         - ../output:/usr/local/spark/output # Output folder

    # spark-worker-3:
    #     image: bitnami/spark:3.1.2
    #     user: root
    #     networks:
    #         - default_net
    #     environment:
    #         - SPARK_MODE=worker
    #         - SPARK_MASTER_URL=spark://spark:7077
    #         - SPARK_WORKER_MEMORY=1G
    #         - SPARK_WORKER_CORES=1
    #         - SPARK_RPC_AUTHENTICATION_ENABLED=no
    #         - SPARK_RPC_ENCRYPTION_ENABLED=no
    #         - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    #         - SPARK_SSL_ENABLED=no
    #     volumes:
    #         - ../spark/app:/usr/local/spark/app # Spark scripts folder (Must be the same path in airflow and Spark Cluster)
    #         - ../spark/resources:/usr/local/spark/resources #Resources folder (Must be the same path in airflow and Spark Cluster)
    #         - ../output:/usr/local/spark/output # Output folder

    #Jupyter notebook
    jupyter-spark:
        image: jupyter/pyspark-notebook:spark-3.3.0
        networks:
            - default_net
        ports:
            - "8888:8888"
            - "4040-4080:4040-4080"
        volumes:
            - ../notebooks:/home/jovyan/work/notebooks/
            - ../output:/home/jovyan/work/output/
            - ../spark/resources/data:/home/jovyan/work/data/
            - ../spark/resources/jars:/home/jovyan/work/jars/

    clickhouse-server:
        image: yandex/clickhouse-server:21.3.20.1
        networks:
            - default_net
        ports:
            - "8123:8123"
            - "9000:9000"
            - "9009:9009"

        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144

networks:
    default_net:
